// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.17.2
// source: msg.go

package simplex

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__canotoEmptyVoteMetadata__Epoch__tag = "\x10" // canoto.Tag(2, canoto.Varint)
	canoto__canotoEmptyVoteMetadata__Round__tag = "\x20" // canoto.Tag(4, canoto.Varint)
)

type canotoData_canotoEmptyVoteMetadata struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*canotoEmptyVoteMetadata) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero canotoEmptyVoteMetadata
	s := &canoto.Spec{
		Name: "canotoEmptyVoteMetadata",
		Fields: []canoto.FieldType{
			{
				FieldNumber: 2,
				Name:        "Epoch",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.Epoch),
			},
			{
				FieldNumber: 4,
				Name:        "Round",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.Round),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*canotoEmptyVoteMetadata) MakeCanoto() *canotoEmptyVoteMetadata {
	return new(canotoEmptyVoteMetadata)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *canotoEmptyVoteMetadata) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *canotoEmptyVoteMetadata) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = canotoEmptyVoteMetadata{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 2:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.Epoch); err != nil {
				return err
			}
			if canoto.IsZero(c.Epoch) {
				return canoto.ErrZeroValue
			}
		case 4:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.Round); err != nil {
				return err
			}
			if canoto.IsZero(c.Round) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *canotoEmptyVoteMetadata) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *canotoEmptyVoteMetadata) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.Epoch) {
		size += uint64(len(canoto__canotoEmptyVoteMetadata__Epoch__tag)) + canoto.SizeUint(c.Epoch)
	}
	if !canoto.IsZero(c.Round) {
		size += uint64(len(canoto__canotoEmptyVoteMetadata__Round__tag)) + canoto.SizeUint(c.Round)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *canotoEmptyVoteMetadata) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *canotoEmptyVoteMetadata) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *canotoEmptyVoteMetadata) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.Epoch) {
		canoto.Append(&w, canoto__canotoEmptyVoteMetadata__Epoch__tag)
		canoto.AppendUint(&w, c.Epoch)
	}
	if !canoto.IsZero(c.Round) {
		canoto.Append(&w, canoto__canotoEmptyVoteMetadata__Round__tag)
		canoto.AppendUint(&w, c.Round)
	}
	return w
}
