// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/simplex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Round         uint64                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Prev          []byte                 `protobuf:"bytes,5,opt,name=prev,proto3" json:"prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMetadata) Reset() {
	*x = ProtocolMetadata{}
	mi := &file_proto_simplex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMetadata) ProtoMessage() {}

func (x *ProtocolMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMetadata.ProtoReflect.Descriptor instead.
func (*ProtocolMetadata) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolMetadata) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProtocolMetadata) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ProtocolMetadata) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ProtocolMetadata) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ProtocolMetadata) GetPrev() []byte {
	if x != nil {
		return x.Prev
	}
	return nil
}

type BlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ProtocolMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_proto_simplex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeader) GetMetadata() *ProtocolMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BlockHeader) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signer        []byte                 `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_proto_simplex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{2}
}

func (x *Signature) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

func (x *Signature) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type QuorumCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signers       [][]byte               `protobuf:"bytes,1,rep,name=signers,proto3" json:"signers,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumCertificate) Reset() {
	*x = QuorumCertificate{}
	mi := &file_proto_simplex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCertificate) ProtoMessage() {}

func (x *QuorumCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCertificate.ProtoReflect.Descriptor instead.
func (*QuorumCertificate) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{3}
}

func (x *QuorumCertificate) GetSigners() [][]byte {
	if x != nil {
		return x.Signers
	}
	return nil
}

func (x *QuorumCertificate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeader   *BlockHeader           `protobuf:"bytes,1,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_proto_simplex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{4}
}

func (x *Vote) GetBlockHeader() *BlockHeader {
	if x != nil {
		return x.BlockHeader
	}
	return nil
}

func (x *Vote) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EmptyVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Signature     *Signature             `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyVote) Reset() {
	*x = EmptyVote{}
	mi := &file_proto_simplex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyVote) ProtoMessage() {}

func (x *EmptyVote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyVote.ProtoReflect.Descriptor instead.
func (*EmptyVote) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{5}
}

func (x *EmptyVote) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *EmptyVote) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EmptyVote) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type FinalizeVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeader   *BlockHeader           `protobuf:"bytes,1,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeVote) Reset() {
	*x = FinalizeVote{}
	mi := &file_proto_simplex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeVote) ProtoMessage() {}

func (x *FinalizeVote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeVote.ProtoReflect.Descriptor instead.
func (*FinalizeVote) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{6}
}

func (x *FinalizeVote) GetBlockHeader() *BlockHeader {
	if x != nil {
		return x.BlockHeader
	}
	return nil
}

func (x *FinalizeVote) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Notarization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeader   *BlockHeader           `protobuf:"bytes,1,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	Qc            *QuorumCertificate     `protobuf:"bytes,2,opt,name=qc,proto3" json:"qc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notarization) Reset() {
	*x = Notarization{}
	mi := &file_proto_simplex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notarization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notarization) ProtoMessage() {}

func (x *Notarization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notarization.ProtoReflect.Descriptor instead.
func (*Notarization) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{7}
}

func (x *Notarization) GetBlockHeader() *BlockHeader {
	if x != nil {
		return x.BlockHeader
	}
	return nil
}

func (x *Notarization) GetQc() *QuorumCertificate {
	if x != nil {
		return x.Qc
	}
	return nil
}

type EmptyNotarization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Qc            *QuorumCertificate     `protobuf:"bytes,3,opt,name=qc,proto3" json:"qc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyNotarization) Reset() {
	*x = EmptyNotarization{}
	mi := &file_proto_simplex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyNotarization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyNotarization) ProtoMessage() {}

func (x *EmptyNotarization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyNotarization.ProtoReflect.Descriptor instead.
func (*EmptyNotarization) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{8}
}

func (x *EmptyNotarization) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *EmptyNotarization) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EmptyNotarization) GetQc() *QuorumCertificate {
	if x != nil {
		return x.Qc
	}
	return nil
}

type Finalization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeader   *BlockHeader           `protobuf:"bytes,1,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	Qc            *QuorumCertificate     `protobuf:"bytes,2,opt,name=qc,proto3" json:"qc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finalization) Reset() {
	*x = Finalization{}
	mi := &file_proto_simplex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finalization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finalization) ProtoMessage() {}

func (x *Finalization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finalization.ProtoReflect.Descriptor instead.
func (*Finalization) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{9}
}

func (x *Finalization) GetBlockHeader() *BlockHeader {
	if x != nil {
		return x.BlockHeader
	}
	return nil
}

func (x *Finalization) GetQc() *QuorumCertificate {
	if x != nil {
		return x.Qc
	}
	return nil
}

type BlockMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockBytes    []byte                 `protobuf:"bytes,1,opt,name=block_bytes,json=blockBytes,proto3" json:"block_bytes,omitempty"`
	Vote          *Vote                  `protobuf:"bytes,2,opt,name=vote,proto3" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMessage) Reset() {
	*x = BlockMessage{}
	mi := &file_proto_simplex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMessage) ProtoMessage() {}

func (x *BlockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMessage.ProtoReflect.Descriptor instead.
func (*BlockMessage) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{10}
}

func (x *BlockMessage) GetBlockBytes() []byte {
	if x != nil {
		return x.BlockBytes
	}
	return nil
}

func (x *BlockMessage) GetVote() *Vote {
	if x != nil {
		return x.Vote
	}
	return nil
}

type QuorumRound struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BlockBytes        []byte                 `protobuf:"bytes,1,opt,name=block_bytes,json=blockBytes,proto3" json:"block_bytes,omitempty"`
	Notarization      *Notarization          `protobuf:"bytes,2,opt,name=notarization,proto3,oneof" json:"notarization,omitempty"`
	Finalization      *Finalization          `protobuf:"bytes,3,opt,name=finalization,proto3,oneof" json:"finalization,omitempty"`
	EmptyNotarization *EmptyNotarization     `protobuf:"bytes,4,opt,name=empty_notarization,json=emptyNotarization,proto3,oneof" json:"empty_notarization,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuorumRound) Reset() {
	*x = QuorumRound{}
	mi := &file_proto_simplex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumRound) ProtoMessage() {}

func (x *QuorumRound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumRound.ProtoReflect.Descriptor instead.
func (*QuorumRound) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{11}
}

func (x *QuorumRound) GetBlockBytes() []byte {
	if x != nil {
		return x.BlockBytes
	}
	return nil
}

func (x *QuorumRound) GetNotarization() *Notarization {
	if x != nil {
		return x.Notarization
	}
	return nil
}

func (x *QuorumRound) GetFinalization() *Finalization {
	if x != nil {
		return x.Finalization
	}
	return nil
}

func (x *QuorumRound) GetEmptyNotarization() *EmptyNotarization {
	if x != nil {
		return x.EmptyNotarization
	}
	return nil
}

type ReplicationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Seqs               []uint64               `protobuf:"varint,1,rep,packed,name=seqs,proto3" json:"seqs,omitempty"`
	Rounds             []uint64               `protobuf:"varint,2,rep,packed,name=rounds,proto3" json:"rounds,omitempty"`
	LatestRound        uint64                 `protobuf:"varint,3,opt,name=latest_round,json=latestRound,proto3" json:"latest_round,omitempty"`
	LatestFinalizedSeq uint64                 `protobuf:"varint,4,opt,name=latest_finalized_seq,json=latestFinalizedSeq,proto3" json:"latest_finalized_seq,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	mi := &file_proto_simplex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{12}
}

func (x *ReplicationRequest) GetSeqs() []uint64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

func (x *ReplicationRequest) GetRounds() []uint64 {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *ReplicationRequest) GetLatestRound() uint64 {
	if x != nil {
		return x.LatestRound
	}
	return 0
}

func (x *ReplicationRequest) GetLatestFinalizedSeq() uint64 {
	if x != nil {
		return x.LatestFinalizedSeq
	}
	return 0
}

type ReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*QuorumRound         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	LatestRound   *QuorumRound           `protobuf:"bytes,2,opt,name=latest_round,json=latestRound,proto3,oneof" json:"latest_round,omitempty"`
	LatestSeq     *QuorumRound           `protobuf:"bytes,3,opt,name=latest_seq,json=latestSeq,proto3,oneof" json:"latest_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationResponse) Reset() {
	*x = ReplicationResponse{}
	mi := &file_proto_simplex_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationResponse) ProtoMessage() {}

func (x *ReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationResponse.ProtoReflect.Descriptor instead.
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{13}
}

func (x *ReplicationResponse) GetData() []*QuorumRound {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReplicationResponse) GetLatestRound() *QuorumRound {
	if x != nil {
		return x.LatestRound
	}
	return nil
}

func (x *ReplicationResponse) GetLatestSeq() *QuorumRound {
	if x != nil {
		return x.LatestSeq
	}
	return nil
}

type BlockDigestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDigestRequest) Reset() {
	*x = BlockDigestRequest{}
	mi := &file_proto_simplex_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDigestRequest) ProtoMessage() {}

func (x *BlockDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDigestRequest.ProtoReflect.Descriptor instead.
func (*BlockDigestRequest) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{14}
}

func (x *BlockDigestRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *BlockDigestRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type SimplexMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SimplexMessage_BlockMessage
	//	*SimplexMessage_VoteMessage
	//	*SimplexMessage_EmptyVoteMessage
	//	*SimplexMessage_Notarization
	//	*SimplexMessage_EmptyNotarization
	//	*SimplexMessage_FinalizeVote
	//	*SimplexMessage_Finalization
	//	*SimplexMessage_ReplicationRequest
	//	*SimplexMessage_ReplicationResponse
	//	*SimplexMessage_BlockDigestRequest
	Payload       isSimplexMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimplexMessage) Reset() {
	*x = SimplexMessage{}
	mi := &file_proto_simplex_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimplexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplexMessage) ProtoMessage() {}

func (x *SimplexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplexMessage.ProtoReflect.Descriptor instead.
func (*SimplexMessage) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{15}
}

func (x *SimplexMessage) GetPayload() isSimplexMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SimplexMessage) GetBlockMessage() *BlockMessage {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_BlockMessage); ok {
			return x.BlockMessage
		}
	}
	return nil
}

func (x *SimplexMessage) GetVoteMessage() *Vote {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_VoteMessage); ok {
			return x.VoteMessage
		}
	}
	return nil
}

func (x *SimplexMessage) GetEmptyVoteMessage() *EmptyVote {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_EmptyVoteMessage); ok {
			return x.EmptyVoteMessage
		}
	}
	return nil
}

func (x *SimplexMessage) GetNotarization() *Notarization {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_Notarization); ok {
			return x.Notarization
		}
	}
	return nil
}

func (x *SimplexMessage) GetEmptyNotarization() *EmptyNotarization {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_EmptyNotarization); ok {
			return x.EmptyNotarization
		}
	}
	return nil
}

func (x *SimplexMessage) GetFinalizeVote() *FinalizeVote {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_FinalizeVote); ok {
			return x.FinalizeVote
		}
	}
	return nil
}

func (x *SimplexMessage) GetFinalization() *Finalization {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_Finalization); ok {
			return x.Finalization
		}
	}
	return nil
}

func (x *SimplexMessage) GetReplicationRequest() *ReplicationRequest {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_ReplicationRequest); ok {
			return x.ReplicationRequest
		}
	}
	return nil
}

func (x *SimplexMessage) GetReplicationResponse() *ReplicationResponse {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_ReplicationResponse); ok {
			return x.ReplicationResponse
		}
	}
	return nil
}

func (x *SimplexMessage) GetBlockDigestRequest() *BlockDigestRequest {
	if x != nil {
		if x, ok := x.Payload.(*SimplexMessage_BlockDigestRequest); ok {
			return x.BlockDigestRequest
		}
	}
	return nil
}

type isSimplexMessage_Payload interface {
	isSimplexMessage_Payload()
}

type SimplexMessage_BlockMessage struct {
	BlockMessage *BlockMessage `protobuf:"bytes,1,opt,name=block_message,json=blockMessage,proto3,oneof"`
}

type SimplexMessage_VoteMessage struct {
	VoteMessage *Vote `protobuf:"bytes,2,opt,name=vote_message,json=voteMessage,proto3,oneof"`
}

type SimplexMessage_EmptyVoteMessage struct {
	EmptyVoteMessage *EmptyVote `protobuf:"bytes,3,opt,name=empty_vote_message,json=emptyVoteMessage,proto3,oneof"`
}

type SimplexMessage_Notarization struct {
	Notarization *Notarization `protobuf:"bytes,4,opt,name=notarization,proto3,oneof"`
}

type SimplexMessage_EmptyNotarization struct {
	EmptyNotarization *EmptyNotarization `protobuf:"bytes,5,opt,name=empty_notarization,json=emptyNotarization,proto3,oneof"`
}

type SimplexMessage_FinalizeVote struct {
	FinalizeVote *FinalizeVote `protobuf:"bytes,6,opt,name=finalize_vote,json=finalizeVote,proto3,oneof"`
}

type SimplexMessage_Finalization struct {
	Finalization *Finalization `protobuf:"bytes,7,opt,name=finalization,proto3,oneof"`
}

type SimplexMessage_ReplicationRequest struct {
	ReplicationRequest *ReplicationRequest `protobuf:"bytes,8,opt,name=replication_request,json=replicationRequest,proto3,oneof"`
}

type SimplexMessage_ReplicationResponse struct {
	ReplicationResponse *ReplicationResponse `protobuf:"bytes,9,opt,name=replication_response,json=replicationResponse,proto3,oneof"`
}

type SimplexMessage_BlockDigestRequest struct {
	BlockDigestRequest *BlockDigestRequest `protobuf:"bytes,10,opt,name=block_digest_request,json=blockDigestRequest,proto3,oneof"`
}

func (*SimplexMessage_BlockMessage) isSimplexMessage_Payload() {}

func (*SimplexMessage_VoteMessage) isSimplexMessage_Payload() {}

func (*SimplexMessage_EmptyVoteMessage) isSimplexMessage_Payload() {}

func (*SimplexMessage_Notarization) isSimplexMessage_Payload() {}

func (*SimplexMessage_EmptyNotarization) isSimplexMessage_Payload() {}

func (*SimplexMessage_FinalizeVote) isSimplexMessage_Payload() {}

func (*SimplexMessage_Finalization) isSimplexMessage_Payload() {}

func (*SimplexMessage_ReplicationRequest) isSimplexMessage_Payload() {}

func (*SimplexMessage_ReplicationResponse) isSimplexMessage_Payload() {}

func (*SimplexMessage_BlockDigestRequest) isSimplexMessage_Payload() {}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          []byte                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Message       *SimplexMessage        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_simplex_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{16}
}

func (x *SendMessageRequest) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SendMessageRequest) GetMessage() *SimplexMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_simplex_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{17}
}

type SubmitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_proto_simplex_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{18}
}

func (x *SubmitTransactionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubmitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_proto_simplex_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{19}
}

func (x *SubmitTransactionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_simplex_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{20}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_simplex_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{21}
}

func (x *GetStatusResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *GetStatusResponse) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *GetStatusResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type GetCommittedBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSeq       uint64                 `protobuf:"varint,1,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommittedBlocksRequest) Reset() {
	*x = GetCommittedBlocksRequest{}
	mi := &file_proto_simplex_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommittedBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommittedBlocksRequest) ProtoMessage() {}

func (x *GetCommittedBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommittedBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetCommittedBlocksRequest) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{22}
}

func (x *GetCommittedBlocksRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type CommittedBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Round         uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Digest        []byte                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommittedBlock) Reset() {
	*x = CommittedBlock{}
	mi := &file_proto_simplex_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommittedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommittedBlock) ProtoMessage() {}

func (x *CommittedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommittedBlock.ProtoReflect.Descriptor instead.
func (*CommittedBlock) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{23}
}

func (x *CommittedBlock) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CommittedBlock) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CommittedBlock) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *CommittedBlock) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type GetCommittedBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*CommittedBlock      `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommittedBlocksResponse) Reset() {
	*x = GetCommittedBlocksResponse{}
	mi := &file_proto_simplex_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommittedBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommittedBlocksResponse) ProtoMessage() {}

func (x *GetCommittedBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommittedBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetCommittedBlocksResponse) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{24}
}

func (x *GetCommittedBlocksResponse) GetBlocks() []*CommittedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type PartitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerIds       [][]byte               `protobuf:"bytes,1,rep,name=peer_ids,json=peerIds,proto3" json:"peer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionRequest) Reset() {
	*x = PartitionRequest{}
	mi := &file_proto_simplex_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionRequest) ProtoMessage() {}

func (x *PartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionRequest.ProtoReflect.Descriptor instead.
func (*PartitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{25}
}

func (x *PartitionRequest) GetPeerIds() [][]byte {
	if x != nil {
		return x.PeerIds
	}
	return nil
}

type PartitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionResponse) Reset() {
	*x = PartitionResponse{}
	mi := &file_proto_simplex_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionResponse) ProtoMessage() {}

func (x *PartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionResponse.ProtoReflect.Descriptor instead.
func (*PartitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{26}
}

type HealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerIds       [][]byte               `protobuf:"bytes,1,rep,name=peer_ids,json=peerIds,proto3" json:"peer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealRequest) Reset() {
	*x = HealRequest{}
	mi := &file_proto_simplex_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealRequest) ProtoMessage() {}

func (x *HealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealRequest.ProtoReflect.Descriptor instead.
func (*HealRequest) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{27}
}

func (x *HealRequest) GetPeerIds() [][]byte {
	if x != nil {
		return x.PeerIds
	}
	return nil
}

type HealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealResponse) Reset() {
	*x = HealResponse{}
	mi := &file_proto_simplex_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealResponse) ProtoMessage() {}

func (x *HealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simplex_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealResponse.ProtoReflect.Descriptor instead.
func (*HealResponse) Descriptor() ([]byte, []int) {
	return file_proto_simplex_proto_rawDescGZIP(), []int{28}
}

var File_proto_simplex_proto protoreflect.FileDescriptor

const file_proto_simplex_proto_rawDesc = "" +
	"\n" +
	"\x13proto/simplex.proto\x12\asimplex\"~\n" +
	"\x10ProtocolMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x04R\x05round\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04prev\x18\x05 \x01(\fR\x04prev\"\\\n" +
	"\vBlockHeader\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.simplex.ProtocolMetadataR\bmetadata\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\"9\n" +
	"\tSignature\x12\x16\n" +
	"\x06signer\x18\x01 \x01(\fR\x06signer\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"A\n" +
	"\x11QuorumCertificate\x12\x18\n" +
	"\asigners\x18\x01 \x03(\fR\asigners\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"q\n" +
	"\x04Vote\x127\n" +
	"\fblock_header\x18\x01 \x01(\v2\x14.simplex.BlockHeaderR\vblockHeader\x120\n" +
	"\tsignature\x18\x02 \x01(\v2\x12.simplex.SignatureR\tsignature\"i\n" +
	"\tEmptyVote\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x120\n" +
	"\tsignature\x18\x03 \x01(\v2\x12.simplex.SignatureR\tsignature\"y\n" +
	"\fFinalizeVote\x127\n" +
	"\fblock_header\x18\x01 \x01(\v2\x14.simplex.BlockHeaderR\vblockHeader\x120\n" +
	"\tsignature\x18\x02 \x01(\v2\x12.simplex.SignatureR\tsignature\"s\n" +
	"\fNotarization\x127\n" +
	"\fblock_header\x18\x01 \x01(\v2\x14.simplex.BlockHeaderR\vblockHeader\x12*\n" +
	"\x02qc\x18\x02 \x01(\v2\x1a.simplex.QuorumCertificateR\x02qc\"k\n" +
	"\x11EmptyNotarization\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12*\n" +
	"\x02qc\x18\x03 \x01(\v2\x1a.simplex.QuorumCertificateR\x02qc\"s\n" +
	"\fFinalization\x127\n" +
	"\fblock_header\x18\x01 \x01(\v2\x14.simplex.BlockHeaderR\vblockHeader\x12*\n" +
	"\x02qc\x18\x02 \x01(\v2\x1a.simplex.QuorumCertificateR\x02qc\"R\n" +
	"\fBlockMessage\x12\x1f\n" +
	"\vblock_bytes\x18\x01 \x01(\fR\n" +
	"blockBytes\x12!\n" +
	"\x04vote\x18\x02 \x01(\v2\r.simplex.VoteR\x04vote\"\xb7\x02\n" +
	"\vQuorumRound\x12\x1f\n" +
	"\vblock_bytes\x18\x01 \x01(\fR\n" +
	"blockBytes\x12>\n" +
	"\fnotarization\x18\x02 \x01(\v2\x15.simplex.NotarizationH\x00R\fnotarization\x88\x01\x01\x12>\n" +
	"\ffinalization\x18\x03 \x01(\v2\x15.simplex.FinalizationH\x01R\ffinalization\x88\x01\x01\x12N\n" +
	"\x12empty_notarization\x18\x04 \x01(\v2\x1a.simplex.EmptyNotarizationH\x02R\x11emptyNotarization\x88\x01\x01B\x0f\n" +
	"\r_notarizationB\x0f\n" +
	"\r_finalizationB\x15\n" +
	"\x13_empty_notarization\"\x95\x01\n" +
	"\x12ReplicationRequest\x12\x12\n" +
	"\x04seqs\x18\x01 \x03(\x04R\x04seqs\x12\x16\n" +
	"\x06rounds\x18\x02 \x03(\x04R\x06rounds\x12!\n" +
	"\flatest_round\x18\x03 \x01(\x04R\vlatestRound\x120\n" +
	"\x14latest_finalized_seq\x18\x04 \x01(\x04R\x12latestFinalizedSeq\"\xd7\x01\n" +
	"\x13ReplicationResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.simplex.QuorumRoundR\x04data\x12<\n" +
	"\flatest_round\x18\x02 \x01(\v2\x14.simplex.QuorumRoundH\x00R\vlatestRound\x88\x01\x01\x128\n" +
	"\n" +
	"latest_seq\x18\x03 \x01(\v2\x14.simplex.QuorumRoundH\x01R\tlatestSeq\x88\x01\x01B\x0f\n" +
	"\r_latest_roundB\r\n" +
	"\v_latest_seq\">\n" +
	"\x12BlockDigestRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\"\xca\x05\n" +
	"\x0eSimplexMessage\x12<\n" +
	"\rblock_message\x18\x01 \x01(\v2\x15.simplex.BlockMessageH\x00R\fblockMessage\x122\n" +
	"\fvote_message\x18\x02 \x01(\v2\r.simplex.VoteH\x00R\vvoteMessage\x12B\n" +
	"\x12empty_vote_message\x18\x03 \x01(\v2\x12.simplex.EmptyVoteH\x00R\x10emptyVoteMessage\x12;\n" +
	"\fnotarization\x18\x04 \x01(\v2\x15.simplex.NotarizationH\x00R\fnotarization\x12K\n" +
	"\x12empty_notarization\x18\x05 \x01(\v2\x1a.simplex.EmptyNotarizationH\x00R\x11emptyNotarization\x12<\n" +
	"\rfinalize_vote\x18\x06 \x01(\v2\x15.simplex.FinalizeVoteH\x00R\ffinalizeVote\x12;\n" +
	"\ffinalization\x18\a \x01(\v2\x15.simplex.FinalizationH\x00R\ffinalization\x12N\n" +
	"\x13replication_request\x18\b \x01(\v2\x1b.simplex.ReplicationRequestH\x00R\x12replicationRequest\x12Q\n" +
	"\x14replication_response\x18\t \x01(\v2\x1c.simplex.ReplicationResponseH\x00R\x13replicationResponse\x12O\n" +
	"\x14block_digest_request\x18\n" +
	" \x01(\v2\x1b.simplex.BlockDigestRequestH\x00R\x12blockDigestRequestB\t\n" +
	"\apayload\"[\n" +
	"\x12SendMessageRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x121\n" +
	"\amessage\x18\x02 \x01(\v2\x17.simplex.SimplexMessageR\amessage\"\x15\n" +
	"\x13SendMessageResponse\".\n" +
	"\x18SubmitTransactionRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"7\n" +
	"\x19SubmitTransactionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x12\n" +
	"\x10GetStatusRequest\"Q\n" +
	"\x11GetStatusResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"6\n" +
	"\x19GetCommittedBlocksRequest\x12\x19\n" +
	"\bfrom_seq\x18\x01 \x01(\x04R\afromSeq\"f\n" +
	"\x0eCommittedBlock\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\fR\x06digest\"M\n" +
	"\x1aGetCommittedBlocksResponse\x12/\n" +
	"\x06blocks\x18\x01 \x03(\v2\x17.simplex.CommittedBlockR\x06blocks\"-\n" +
	"\x10PartitionRequest\x12\x19\n" +
	"\bpeer_ids\x18\x01 \x03(\fR\apeerIds\"\x13\n" +
	"\x11PartitionResponse\"(\n" +
	"\vHealRequest\x12\x19\n" +
	"\bpeer_ids\x18\x01 \x03(\fR\apeerIds\"\x0e\n" +
	"\fHealResponse2W\n" +
	"\vNodeService\x12H\n" +
	"\vSendMessage\x12\x1b.simplex.SendMessageRequest\x1a\x1c.simplex.SendMessageResponse2\x8f\x02\n" +
	"\x0eControlService\x12Z\n" +
	"\x11SubmitTransaction\x12!.simplex.SubmitTransactionRequest\x1a\".simplex.SubmitTransactionResponse\x12B\n" +
	"\tGetStatus\x12\x19.simplex.GetStatusRequest\x1a\x1a.simplex.GetStatusResponse\x12]\n" +
	"\x12GetCommittedBlocks\x12\".simplex.GetCommittedBlocksRequest\x1a#.simplex.GetCommittedBlocksResponse2\x87\x01\n" +
	"\fAdminService\x12B\n" +
	"\tPartition\x12\x19.simplex.PartitionRequest\x1a\x1a.simplex.PartitionResponse\x123\n" +
	"\x04Heal\x12\x14.simplex.HealRequest\x1a\x15.simplex.HealResponseB/Z-github.com/ava-labs/simplex/jepsen/node/protob\x06proto3"

var (
	file_proto_simplex_proto_rawDescOnce sync.Once
	file_proto_simplex_proto_rawDescData []byte
)

func file_proto_simplex_proto_rawDescGZIP() []byte {
	file_proto_simplex_proto_rawDescOnce.Do(func() {
		file_proto_simplex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simplex_proto_rawDesc), len(file_proto_simplex_proto_rawDesc)))
	})
	return file_proto_simplex_proto_rawDescData
}

var file_proto_simplex_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_simplex_proto_goTypes = []any{
	(*ProtocolMetadata)(nil),           // 0: simplex.ProtocolMetadata
	(*BlockHeader)(nil),                // 1: simplex.BlockHeader
	(*Signature)(nil),                  // 2: simplex.Signature
	(*QuorumCertificate)(nil),          // 3: simplex.QuorumCertificate
	(*Vote)(nil),                       // 4: simplex.Vote
	(*EmptyVote)(nil),                  // 5: simplex.EmptyVote
	(*FinalizeVote)(nil),               // 6: simplex.FinalizeVote
	(*Notarization)(nil),               // 7: simplex.Notarization
	(*EmptyNotarization)(nil),          // 8: simplex.EmptyNotarization
	(*Finalization)(nil),               // 9: simplex.Finalization
	(*BlockMessage)(nil),               // 10: simplex.BlockMessage
	(*QuorumRound)(nil),                // 11: simplex.QuorumRound
	(*ReplicationRequest)(nil),         // 12: simplex.ReplicationRequest
	(*ReplicationResponse)(nil),        // 13: simplex.ReplicationResponse
	(*BlockDigestRequest)(nil),         // 14: simplex.BlockDigestRequest
	(*SimplexMessage)(nil),             // 15: simplex.SimplexMessage
	(*SendMessageRequest)(nil),         // 16: simplex.SendMessageRequest
	(*SendMessageResponse)(nil),        // 17: simplex.SendMessageResponse
	(*SubmitTransactionRequest)(nil),   // 18: simplex.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil),  // 19: simplex.SubmitTransactionResponse
	(*GetStatusRequest)(nil),           // 20: simplex.GetStatusRequest
	(*GetStatusResponse)(nil),          // 21: simplex.GetStatusResponse
	(*GetCommittedBlocksRequest)(nil),  // 22: simplex.GetCommittedBlocksRequest
	(*CommittedBlock)(nil),             // 23: simplex.CommittedBlock
	(*GetCommittedBlocksResponse)(nil), // 24: simplex.GetCommittedBlocksResponse
	(*PartitionRequest)(nil),           // 25: simplex.PartitionRequest
	(*PartitionResponse)(nil),          // 26: simplex.PartitionResponse
	(*HealRequest)(nil),                // 27: simplex.HealRequest
	(*HealResponse)(nil),               // 28: simplex.HealResponse
}
var file_proto_simplex_proto_depIdxs = []int32{
	0,  // 0: simplex.BlockHeader.metadata:type_name -> simplex.ProtocolMetadata
	1,  // 1: simplex.Vote.block_header:type_name -> simplex.BlockHeader
	2,  // 2: simplex.Vote.signature:type_name -> simplex.Signature
	2,  // 3: simplex.EmptyVote.signature:type_name -> simplex.Signature
	1,  // 4: simplex.FinalizeVote.block_header:type_name -> simplex.BlockHeader
	2,  // 5: simplex.FinalizeVote.signature:type_name -> simplex.Signature
	1,  // 6: simplex.Notarization.block_header:type_name -> simplex.BlockHeader
	3,  // 7: simplex.Notarization.qc:type_name -> simplex.QuorumCertificate
	3,  // 8: simplex.EmptyNotarization.qc:type_name -> simplex.QuorumCertificate
	1,  // 9: simplex.Finalization.block_header:type_name -> simplex.BlockHeader
	3,  // 10: simplex.Finalization.qc:type_name -> simplex.QuorumCertificate
	4,  // 11: simplex.BlockMessage.vote:type_name -> simplex.Vote
	7,  // 12: simplex.QuorumRound.notarization:type_name -> simplex.Notarization
	9,  // 13: simplex.QuorumRound.finalization:type_name -> simplex.Finalization
	8,  // 14: simplex.QuorumRound.empty_notarization:type_name -> simplex.EmptyNotarization
	11, // 15: simplex.ReplicationResponse.data:type_name -> simplex.QuorumRound
	11, // 16: simplex.ReplicationResponse.latest_round:type_name -> simplex.QuorumRound
	11, // 17: simplex.ReplicationResponse.latest_seq:type_name -> simplex.QuorumRound
	10, // 18: simplex.SimplexMessage.block_message:type_name -> simplex.BlockMessage
	4,  // 19: simplex.SimplexMessage.vote_message:type_name -> simplex.Vote
	5,  // 20: simplex.SimplexMessage.empty_vote_message:type_name -> simplex.EmptyVote
	7,  // 21: simplex.SimplexMessage.notarization:type_name -> simplex.Notarization
	8,  // 22: simplex.SimplexMessage.empty_notarization:type_name -> simplex.EmptyNotarization
	6,  // 23: simplex.SimplexMessage.finalize_vote:type_name -> simplex.FinalizeVote
	9,  // 24: simplex.SimplexMessage.finalization:type_name -> simplex.Finalization
	12, // 25: simplex.SimplexMessage.replication_request:type_name -> simplex.ReplicationRequest
	13, // 26: simplex.SimplexMessage.replication_response:type_name -> simplex.ReplicationResponse
	14, // 27: simplex.SimplexMessage.block_digest_request:type_name -> simplex.BlockDigestRequest
	15, // 28: simplex.SendMessageRequest.message:type_name -> simplex.SimplexMessage
	23, // 29: simplex.GetCommittedBlocksResponse.blocks:type_name -> simplex.CommittedBlock
	16, // 30: simplex.NodeService.SendMessage:input_type -> simplex.SendMessageRequest
	18, // 31: simplex.ControlService.SubmitTransaction:input_type -> simplex.SubmitTransactionRequest
	20, // 32: simplex.ControlService.GetStatus:input_type -> simplex.GetStatusRequest
	22, // 33: simplex.ControlService.GetCommittedBlocks:input_type -> simplex.GetCommittedBlocksRequest
	25, // 34: simplex.AdminService.Partition:input_type -> simplex.PartitionRequest
	27, // 35: simplex.AdminService.Heal:input_type -> simplex.HealRequest
	17, // 36: simplex.NodeService.SendMessage:output_type -> simplex.SendMessageResponse
	19, // 37: simplex.ControlService.SubmitTransaction:output_type -> simplex.SubmitTransactionResponse
	21, // 38: simplex.ControlService.GetStatus:output_type -> simplex.GetStatusResponse
	24, // 39: simplex.ControlService.GetCommittedBlocks:output_type -> simplex.GetCommittedBlocksResponse
	26, // 40: simplex.AdminService.Partition:output_type -> simplex.PartitionResponse
	28, // 41: simplex.AdminService.Heal:output_type -> simplex.HealResponse
	36, // [36:42] is the sub-list for method output_type
	30, // [30:36] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_simplex_proto_init() }
func file_proto_simplex_proto_init() {
	if File_proto_simplex_proto != nil {
		return
	}
	file_proto_simplex_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_simplex_proto_msgTypes[13].OneofWrappers = []any{}
	file_proto_simplex_proto_msgTypes[15].OneofWrappers = []any{
		(*SimplexMessage_BlockMessage)(nil),
		(*SimplexMessage_VoteMessage)(nil),
		(*SimplexMessage_EmptyVoteMessage)(nil),
		(*SimplexMessage_Notarization)(nil),
		(*SimplexMessage_EmptyNotarization)(nil),
		(*SimplexMessage_FinalizeVote)(nil),
		(*SimplexMessage_Finalization)(nil),
		(*SimplexMessage_ReplicationRequest)(nil),
		(*SimplexMessage_ReplicationResponse)(nil),
		(*SimplexMessage_BlockDigestRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simplex_proto_rawDesc), len(file_proto_simplex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_simplex_proto_goTypes,
		DependencyIndexes: file_proto_simplex_proto_depIdxs,
		MessageInfos:      file_proto_simplex_proto_msgTypes,
	}.Build()
	File_proto_simplex_proto = out.File
	file_proto_simplex_proto_goTypes = nil
	file_proto_simplex_proto_depIdxs = nil
}
