// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.19.0
// source: msg.go

package common

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var _ = io.ErrUnexpectedEOF

const (
	canotoNumber_AuxiliaryInfo__Version = 1
	canotoNumber_AuxiliaryInfo__Data    = 2

	canotoTag_AuxiliaryInfo__Version = "\x08" // canoto.Tag(canotoNumber_AuxiliaryInfo__Version, canoto.Varint)
	canotoTag_AuxiliaryInfo__Data    = "\x12" // canoto.Tag(canotoNumber_AuxiliaryInfo__Data, canoto.Len)
)

type canotoData_AuxiliaryInfo struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*AuxiliaryInfo) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero AuxiliaryInfo
	s := &canoto.Spec{
		Name: "AuxiliaryInfo",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canotoNumber_AuxiliaryInfo__Version,
				Name:        "Version",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.Version),
			},
			{
				FieldNumber: canotoNumber_AuxiliaryInfo__Data,
				Name:        "Data",
				OneOf:       "",
				TypeBytes:   true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *AuxiliaryInfo) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *AuxiliaryInfo) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = AuxiliaryInfo{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canotoNumber_AuxiliaryInfo__Version:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.Version); err != nil {
				return err
			}
			if canoto.IsZero(c.Version) {
				return canoto.ErrZeroValue
			}
		case canotoNumber_AuxiliaryInfo__Data:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.Data); err != nil {
				return err
			}
			if len(c.Data) == 0 {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *AuxiliaryInfo) ValidCanoto() bool {
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *AuxiliaryInfo) CalculateCanotoCache() {
	var size uint64
	if !canoto.IsZero(c.Version) {
		size += uint64(len(canotoTag_AuxiliaryInfo__Version)) + canoto.SizeUint(c.Version)
	}
	if len(c.Data) != 0 {
		size += uint64(len(canotoTag_AuxiliaryInfo__Data)) + canoto.SizeBytes(c.Data)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *AuxiliaryInfo) CachedCanotoSize() uint64 {
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AuxiliaryInfo) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AuxiliaryInfo) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if !canoto.IsZero(c.Version) {
		canoto.Append(&w, canotoTag_AuxiliaryInfo__Version)
		canoto.AppendUint(&w, c.Version)
	}
	if len(c.Data) != 0 {
		canoto.Append(&w, canotoTag_AuxiliaryInfo__Data)
		canoto.AppendBytes(&w, c.Data)
	}
	return w
}
