// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.19.0
// source: msg.go

package common

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var _ = io.ErrUnexpectedEOF

const (
	canotoNumber_ValidatorSetApproval__NodeID        = 1
	canotoNumber_ValidatorSetApproval__AuxInfoDigest = 2
	canotoNumber_ValidatorSetApproval__PChainHeight  = 3
	canotoNumber_ValidatorSetApproval__Signature     = 4

	canotoTag_ValidatorSetApproval__NodeID        = "\x0a" // canoto.Tag(canotoNumber_ValidatorSetApproval__NodeID, canoto.Len)
	canotoTag_ValidatorSetApproval__AuxInfoDigest = "\x12" // canoto.Tag(canotoNumber_ValidatorSetApproval__AuxInfoDigest, canoto.Len)
	canotoTag_ValidatorSetApproval__PChainHeight  = "\x18" // canoto.Tag(canotoNumber_ValidatorSetApproval__PChainHeight, canoto.Varint)
	canotoTag_ValidatorSetApproval__Signature     = "\x22" // canoto.Tag(canotoNumber_ValidatorSetApproval__Signature, canoto.Len)
)

type canotoData_ValidatorSetApproval struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*ValidatorSetApproval) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero ValidatorSetApproval
	s := &canoto.Spec{
		Name: "ValidatorSetApproval",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    canotoNumber_ValidatorSetApproval__NodeID,
				Name:           "NodeID",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.NodeID)),
			},
			{
				FieldNumber:    canotoNumber_ValidatorSetApproval__AuxInfoDigest,
				Name:           "AuxInfoDigest",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.AuxInfoDigest)),
			},
			{
				FieldNumber: canotoNumber_ValidatorSetApproval__PChainHeight,
				Name:        "PChainHeight",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PChainHeight),
			},
			{
				FieldNumber: canotoNumber_ValidatorSetApproval__Signature,
				Name:        "Signature",
				OneOf:       "",
				TypeBytes:   true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *ValidatorSetApproval) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *ValidatorSetApproval) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = ValidatorSetApproval{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canotoNumber_ValidatorSetApproval__NodeID:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.NodeID)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.NodeID)[:], r.B)
			if canoto.IsZero(c.NodeID) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canotoNumber_ValidatorSetApproval__AuxInfoDigest:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.AuxInfoDigest)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.AuxInfoDigest)[:], r.B)
			if canoto.IsZero(c.AuxInfoDigest) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case canotoNumber_ValidatorSetApproval__PChainHeight:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PChainHeight); err != nil {
				return err
			}
			if canoto.IsZero(c.PChainHeight) {
				return canoto.ErrZeroValue
			}
		case canotoNumber_ValidatorSetApproval__Signature:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBytes(&r, &c.Signature); err != nil {
				return err
			}
			if len(c.Signature) == 0 {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *ValidatorSetApproval) ValidCanoto() bool {
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *ValidatorSetApproval) CalculateCanotoCache() {
	var size uint64
	if !canoto.IsZero(c.NodeID) {
		size += uint64(len(canotoTag_ValidatorSetApproval__NodeID)) + canoto.SizeBytes((&c.NodeID)[:])
	}
	if !canoto.IsZero(c.AuxInfoDigest) {
		size += uint64(len(canotoTag_ValidatorSetApproval__AuxInfoDigest)) + canoto.SizeBytes((&c.AuxInfoDigest)[:])
	}
	if !canoto.IsZero(c.PChainHeight) {
		size += uint64(len(canotoTag_ValidatorSetApproval__PChainHeight)) + canoto.SizeUint(c.PChainHeight)
	}
	if len(c.Signature) != 0 {
		size += uint64(len(canotoTag_ValidatorSetApproval__Signature)) + canoto.SizeBytes(c.Signature)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *ValidatorSetApproval) CachedCanotoSize() uint64 {
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *ValidatorSetApproval) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *ValidatorSetApproval) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if !canoto.IsZero(c.NodeID) {
		canoto.Append(&w, canotoTag_ValidatorSetApproval__NodeID)
		canoto.AppendBytes(&w, (&c.NodeID)[:])
	}
	if !canoto.IsZero(c.AuxInfoDigest) {
		canoto.Append(&w, canotoTag_ValidatorSetApproval__AuxInfoDigest)
		canoto.AppendBytes(&w, (&c.AuxInfoDigest)[:])
	}
	if !canoto.IsZero(c.PChainHeight) {
		canoto.Append(&w, canotoTag_ValidatorSetApproval__PChainHeight)
		canoto.AppendUint(&w, c.PChainHeight)
	}
	if len(c.Signature) != 0 {
		canoto.Append(&w, canotoTag_ValidatorSetApproval__Signature)
		canoto.AppendBytes(&w, c.Signature)
	}
	return w
}
