// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.19.0
// source: auxiliary.go

package metadata

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var _ = io.ErrUnexpectedEOF

const (
	canotoNumber_AuxiliaryInfoBatch__data           = 1
	canotoNumber_AuxiliaryInfoBatch__PrevAuxInfoSeq = 2

	canotoTag_AuxiliaryInfoBatch__data           = "\x0a" // canoto.Tag(canotoNumber_AuxiliaryInfoBatch__data, canoto.Len)
	canotoTag_AuxiliaryInfoBatch__PrevAuxInfoSeq = "\x10" // canoto.Tag(canotoNumber_AuxiliaryInfoBatch__PrevAuxInfoSeq, canoto.Varint)
)

type canotoData_AuxiliaryInfoBatch struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*AuxiliaryInfoBatch) CanotoSpec(types ...reflect.Type) *canoto.Spec {
	types = append(types, reflect.TypeFor[AuxiliaryInfoBatch]())
	var zero AuxiliaryInfoBatch
	s := &canoto.Spec{
		Name: "AuxiliaryInfoBatch",
		Fields: []canoto.FieldType{
			canoto.FieldTypeFromField(
				/*type inference:*/ (canoto.MakeEntryNilPointer(zero.data)),
				/*FieldNumber:   */ canotoNumber_AuxiliaryInfoBatch__data,
				/*Name:          */ "data",
				/*FixedLength:   */ 0,
				/*Repeated:      */ true,
				/*OneOf:         */ "",
				/*Pointer:       */ false,
				/*types:         */ types,
			),
			{
				FieldNumber: canotoNumber_AuxiliaryInfoBatch__PrevAuxInfoSeq,
				Name:        "PrevAuxInfoSeq",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.PrevAuxInfoSeq),
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *AuxiliaryInfoBatch) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *AuxiliaryInfoBatch) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = AuxiliaryInfoBatch{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canotoNumber_AuxiliaryInfoBatch__data:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Read the first entry manually because the tag is already
			// stripped.
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			var msgBytes []byte
			if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canotoTag_AuxiliaryInfoBatch__data)
			if err != nil {
				return err
			}

			c.data = canoto.MakeSlice(c.data, countMinus1+1)
			field := c.data
			additionalField := field[1:]
			if len(msgBytes) != 0 {
				remainingBytes := r.B
				r.B = msgBytes
				if err := (&field[0]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}

			// Read the rest of the entries, stripping the tag each time.
			for i := range additionalField {
				r.B = r.B[len(canotoTag_AuxiliaryInfoBatch__data):]
				r.Unsafe = true
				if err := canoto.ReadBytes(&r, &msgBytes); err != nil {
					return err
				}
				r.Unsafe = originalUnsafe
				if len(msgBytes) == 0 {
					continue
				}

				remainingBytes := r.B
				r.B = msgBytes
				if err := (&additionalField[i]).UnmarshalCanotoFrom(r); err != nil {
					return err
				}
				r.B = remainingBytes
			}
		case canotoNumber_AuxiliaryInfoBatch__PrevAuxInfoSeq:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.PrevAuxInfoSeq); err != nil {
				return err
			}
			if canoto.IsZero(c.PrevAuxInfoSeq) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *AuxiliaryInfoBatch) ValidCanoto() bool {
	{
		field := c.data
		for i := range field {
			if !(&field[i]).ValidCanoto() {
				return false
			}
		}
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *AuxiliaryInfoBatch) CalculateCanotoCache() {
	var size uint64
	{
		field := c.data
		for i := range field {
			(&field[i]).CalculateCanotoCache()
			fieldSize := (&field[i]).CachedCanotoSize()
			size += uint64(len(canotoTag_AuxiliaryInfoBatch__data)) + canoto.SizeUint(fieldSize) + fieldSize
		}
	}
	if !canoto.IsZero(c.PrevAuxInfoSeq) {
		size += uint64(len(canotoTag_AuxiliaryInfoBatch__PrevAuxInfoSeq)) + canoto.SizeUint(c.PrevAuxInfoSeq)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *AuxiliaryInfoBatch) CachedCanotoSize() uint64 {
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AuxiliaryInfoBatch) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AuxiliaryInfoBatch) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	{
		field := c.data
		for i := range field {
			canoto.Append(&w, canotoTag_AuxiliaryInfoBatch__data)
			canoto.AppendUint(&w, (&field[i]).CachedCanotoSize())
			w = (&field[i]).MarshalCanotoInto(w)
		}
	}
	if !canoto.IsZero(c.PrevAuxInfoSeq) {
		canoto.Append(&w, canotoTag_AuxiliaryInfoBatch__PrevAuxInfoSeq)
		canoto.AppendUint(&w, c.PrevAuxInfoSeq)
	}
	return w
}
